name: Go

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Setup runtime
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Check code quality
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=30m

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v ./...

